### ISSUE TITLE
License statement

### ISSUE THREAD

**Issue by fabaff** [Xenios91/Secrets-Extractor#1]
Currently there is no license statement. Could you please add a `LICENSE` file that contains the license text.

This is requirement for some distribution if they want to ship it as package through their repos.

Thanks.

**Comment by fabaff** [comment]
For the [Nixpkgs](https://github.com/NixOS/nixpkgs/pull/178172) I marked it as `unfree` for now. People would still be able to install it but not by default.

**Comment by Xenios91** [comment]
Added an MIT liscense.
